### ISSUE TITLE
Add support for alternate definition configs under .devcontainer

### ISSUE THREAD

**Issue by 2percentsilk** [devcontainers/spec#6] opened 2022-01-21 23:13 UTC
As part of the monorepo support for Codespaces, we want users to be able to choose a devcontainer specific for their scenario from a list of devcontainer definitions contained with the .devcontainer folder. 
For example, they could have .devcontainer/actions/devcontainer.json as well as .devcontainer/vscode/devcontainer.json and providing either path would work and successfully create the dev container specified at that path.

As an example, we'd expect for any of the follow paths to devcontainer definitions to be acceptable:
```
repository_root
 | .devcontainer.json
 |
 | .devcontainer
   |
   +-- foo
   |  |  
   |  +-- devcontainer.json
   |  \-- Dockerfile
   | 
   +-- foo
   |  |  
   |  +-- devcontainer.json 
```

As a stretch, it would be great if the definition could be 2+ folders down such that `.devcontainer/actions/allisb/devcontainer.json` would also work but one subdirectory is sufficient for this first stage.

**Comment by Chuxel** [comment] 2022-01-28 19:42
Related: https://github.com/microsoft/vscode-remote-release/issues/1165

**Comment by chrmarti** [comment] 2022-01-31 15:13
I wonder: Editors and IDEs tend to share project settings using a file or folder in the project folder (`.vimrc`, `.sublime-project`, `.idea`, `.vscode`). Aren't monorepos using one such settings file/folder per sub-project? Would it make sense to align with this and use one `.devcontainer` folder per sub-project in the monorepo? E.g., `<root>/foo/.devcontainer/devcontainer.json` and `<root>/bar/.devcontainer/devcontainer.json` for sub-projects `foo` and `bar`.

**Comment by bamurtaugh** [comment] 2022-01-31 17:00
@chrmarti Would that look like any (or multiple) of the following?

Option one (supporting `.devcontainer.json` and `.devcontainer` in the root, just requiring `.devcontainer` for sub-projects. This would lead to nested `.devcontainer` folders):
```
repository_root
 | .devcontainer.json
 |
 | .devcontainer
   |
   +-- foo
   |  |  
   | .devcontainer
      |  +-- devcontainer.json
      |  \-- Dockerfile
   | 
   +-- foo
   |  |  
   | .devcontainer
      |  +-- devcontainer.json 
```

Two (support `.devcontainer` in the root, but it wouldn't have nested projects / `devcontainer` folders and instead just a root-level `devcontainer.json` and Dockerfile):
```
repository_root
 | .devcontainer.json
 |
 | .devcontainer
    |  +-- devcontainer.json
    |  \-- Dockerfile
 |
 +-- foo
 |  |  
 | .devcontainer
    |  +-- devcontainer.json
    |  \-- Dockerfile
 | 
 +-- foo
 |  |  
 | .devcontainer
    |  +-- devcontainer.json 
```

Three (don't use `.devcontainer` at the root, instead requiring each sub-project to provide `.devcontainer.json`, and still support a root `.devcontainer.json`):
```
repository_root
 | .devcontainer.json
   |
   +-- foo
   |  |  
   | .devcontainer
      |  +-- devcontainer.json
      |  \-- Dockerfile
   | 
   +-- foo
   |  |  
   | .devcontainer
      |  +-- devcontainer.json 
```

Four (no dev container files/folders supported at the root):
```
repository_root
   |
   +-- foo
   |  |  
   | .devcontainer
      |  +-- devcontainer.json
      |  \-- Dockerfile
   | 
   +-- foo
   |  |  
   | .devcontainer
      |  +-- devcontainer.json 
```

I think my main questions are:
- Would we require a `.devcontainer` folder in each sub-project, and remove `.devcontainer` from the root?
- Does this affect what the user can include in the root? i.e. still allow `.devcontainer.json`, still allow or require `.devcontainer` which could include:
     - a root-level `devcontainer.json` and Dockerfile, or
     - Nested `.devcontainer` folders

**Comment by Chuxel** [comment] 2022-01-31 18:34
> I wonder: Editors and IDEs tend to share project settings using a file or folder in the project folder (`.vimrc`, `.sublime-project`, `.idea`, `.vscode`). Aren't monorepos using one such settings file/folder per sub-project? Would it make sense to align with this and use one `.devcontainer` folder per sub-project in the monorepo? E.g., `<root>/foo/.devcontainer/devcontainer.json` and `<root>/bar/.devcontainer/devcontainer.json` for sub-projects `foo` and `bar`.

@chrmarti Yes and no. Sometimes that's the case - but a monorepo can also be for a large single "application". Definatley heard feedback about role specific config - e.g. a front end developer verses back end. In these cases, it's the same "project", but you need multiple "views" on it (e.g. there's potentially multiple `.code-workspace` files).  This is the case that @2percentsilk is trying to address.

If the monorepo is the giant kind that actually crosses multiple applications, then yes, tool specific config would be under a sub-folder, but that's not what this is trying to solve.

**Comment by bamurtaugh** [comment] 2022-02-01 00:17
From my understanding, the main new features here is: VS Code searches for dev container definitions in root and sub-folders. Once VS Code detects all of the sub-definitions, it allows users to pick one when opening their project in a dev container.

Apologies if I'm missing this, but would this ask be just part of the monorepo support? Here users will nest their sub-container definitions in one main `.devcontainer` folder at the root since this type of monorepo involves folks all on the same large repo with different roles. If users have dev containers spread into their sub-projects, rather than all in one central `.devcontainer`, that'd be what @chrmarti was suggesting and @Chuxel described as: 

> If the monorepo is the giant kind that actually crosses multiple applications, then yes, tool specific config would be under a sub-folder, but that's not what this is trying to solve

**Comment by Chuxel** [comment] 2022-02-01 01:19
> Apologies if I'm missing this, but would this ask be just part of / one type of monorepo support? 

Yep, there's two types, one of which we already have covered in the spec even if just partly covered by the products.

1. **Supported now by spec:** Several independent "projects" in a single large repository. This is common with source control systems like Subversion, and in some cases orgs follow this practices in Git as well.  Per the spec, you could run a "dev container CLI" in a sub-folder in the repository that itself has a .devcontainer folder in it. In this case, we still automatically mount the git repository into the container for image/Dockerfile, and users can control the mount in the Docker Compose case per the spec. (Codespaces has product gaps here, and so does Remote - Containers for opening a repo in a container volume, but that's not a spec problem.)

2. **Gap in spec:** Several "views" on the same repository contents based on project/developer role or focus, rather than a single sub-folder. In this case, you likely need multiple sub-folders in the monorepo to build and develop the application. However, different roles have different focuses, extensions, settings, runtimes, etc. There's no single sub-folder to anchor to in determining what to include/not include. The request is to allow multiple variations under the root `.devcontainer` folder. Users that open the root folder can then make a choice as to which one they want to use.

The "workspaceMount" property requires an absolute path for the "source", there's not a good workaround for the second case even with local Remote - Containers.

**Comment by frank-dspeed** [comment] 2022-03-22 18:13
@Chuxel wouldnt it be better to simply share the vscode remote component or at last the installer so that people can simply deploy that and then set any location where that is deployed as target? this way all would be open as it would be needed.

**Comment by Chuxel** [comment] 2022-03-22 18:19
@frank-dspeed Not quite sure what you are getting at by the "vscode remote component". Can you clarifty? There's plans for a reference implementation (see #9) if that's what you're getting at, but that's not related to this topic.

What this is solving providing the ability to have multiple variations of a configuration in a central spot, while still retaining automount behaviors for the repository root. Anyone opening the root repository can them be presented with a list of existing configurations.  You can place devcontainer.json contents in sub-folders today.

**Comment by frank-dspeed** [comment] 2022-03-22 18:35
see: https://github.com/microsoft/vscode/issues/89762 this makes all dev container features obsolet! It makes anything else that belongs to work with remote environments obsolet it is the sucessor of your iteration plan! And i know what i talk i was early adopter and contributor of the libcontainer project / docker / moby 

also i am expert for the successor of containerisation that is WASM 

but first things first promote that issue and you will see how fast the ecosystem growth

**Comment by Chuxel** [comment] 2022-03-22 19:12
Thanks for the feedback - though that's off topic for this issue and really this repository.

What we are discussing here is really about the dev container specification rather than VS Code or the remote extensions themselves. The reference implementation will be OSS (#9) and cover how the needed metadata spins up related containers based on dev container config. This can be used anywhere.  However, since other non-VS Code tools can use it (e.g. CI systems, or anyone else that wants to support the spec), anything specific VS Code itself fits best with the issue you reference or one in https://github.com/microsoft/vscode-remote-release.  VS Code injects what it needs based on the specific commit of the client, so there isn't a generic server pre-se. That said, you can use Remote - SSH and Remote - Containers [in combination now](https://code.visualstudio.com/docs/remote/containers#_open-a-folder-on-a-remote-ssh-host-in-a-container) if that is what you are getting at. (Docker does not need to be installed locally for that.)

**Comment by frank-dspeed** [comment] 2022-03-23 07:09
@Chuxel i mean the relation between the 2 is that we do not need a dev container spec as soon as we are able to configure our own dev containers. https://www.eclipse.org/escet/chi/ demonstrates that well with its Container Definition and Integration layer into Theia https://theia-ide.org/ 

Both got a Better Container Integration then this original VSCODE the only + point for vscode It got more extensions and more extension authors. So Overall Vscode is the better Product but it leaks Remote Dev

**Comment by frank-dspeed** [comment] 2022-03-23 07:15
@Chuxel thanks for the attention. Let me say something short about your offtopic concerns 

Containers are already Nested Defined there are existing Opensource Defintions for that i do not want to list everything my conclusion that is related to the topic is that you should stop implementing a own Definition and should enable usage of Remote Containers as Dev Environment so the Missing part is always only the Interface to the Container or the Container Engine

Not the Definition of Multiple Containers and the Operating System that they run or run not (Containers by design are like Unikernels so they should not depend on a OS at all its a Single Binary as WASM is)

Containers are like a Compiler Target for LLVM 

we got tools like podman (successor of docker) that got for example the so called pod definition which includes everything needed. 

so we can already define Dev Environment Pods the Project Eclipse

**Comment by Chuxel** [comment] 2022-03-23 14:23
@frank-dspeed Happy to talk about this in another thread. I think that there's a bit of confusion here as to what this format is trying to do - which is not define container orchestration. I think what you are talking about is more relevant to #10. There's no intent to replace pods or kubernetes with this format.

**Comment by frank-dspeed** [comment] 2022-03-24 06:55
@Chuxel ok then we should talk here about terraform as that is covering exactly what you describe here https://www.terraform.io/ it describes containers and vms on diffrent infra.

**Comment by twsl** [comment] 2022-04-05 12:05
@frank-dspeed you are basically rooting for the deprecation of the .devcontainer specification in favour of terraform. This has nothing to do with this issue.
But having the opportunity to specify and select from multiple devcontainer variations per project is imo a critical feature for larger projects that is currently missing.

**Comment by frank-dspeed** [comment] 2022-04-06 05:49
@twsl nope terraform is only one of many implementations there are many more only wanted to point to one that is known do not get me wrong I am for innovation but I see innovation blocked because of definitions. There is a lot of overlapping functionality and it takes much time to educate developers. While the features are designed with the goal to less educate the developer. So I want to point out that I see a structural Root Problem with the definition and its progress of it.

The final goal is to enable the following use case:

1. Git Clone Repo. 
2. Open in vscode
3. Get an Offer that you can work in a defined dev container with a fully configured environment for the Project

only if that is wrong so when dev containers are designed for anything else. Then my suggestion is offtopic and then I am wrong.  But if the above is true then I am fully correct with my observation I am 100% sure. But I also understand that I would need to write more Papers about that to convince people that do not have the same experience and knowledge. I Only point that out because i feel it is a urgent observation  and the IDE is the new Teacher of Coders today. So if the teacher is wrong we get a whole bunch of Developers that get a wrong mindset implemented. Its like with Blockchain Containers are a buzz word for many people they get confused by the observations that they are doing they see them as VM's while they are by no means VM's they are Compiler Targets. They are hard linking dependencies.

**Comment by Chuxel** [comment] 2022-04-06 16:11
Please stop discussing this here - it is off topic for the specific issue.  This sounds like the remote extension's attach functionality which is not related to this issue. Thanks!

**Comment by Chuxel** [comment] 2022-05-13 14:12
Codespaces has gone ahead and implemented this capability (https://github.blog/2022-04-20-codespaces-multi-repository-monorepo-scenarios/).  So, it's effectively part of the spec, but #9 will include it once released and Remote - Containers has not yet added support for making the selection via UX.  I think we can close this out once #9 is released.  @bamurtaugh @edgonmsft I know you folks are working on docs - I don't think this support is in the current PRs, correct?

**Comment by bamurtaugh** [comment] 2022-05-13 22:33
Thanks for the tag, Chuck! 

I don't believe so - is there a spot we're envisioning for it to be highlighted in spec materials? Perhaps in https://github.com/devcontainers/spec (@edgonmsft is working on other info for this repo)? I can add it to Remote-Containers docs too whenever it may be supported via the UI.

**Comment by dragon512** [comment] 2023-03-05 20:37
I just wanted to chime in. This feature is what I think I have been looking for. I work on many different open-source projects for my job and it would be of great value to define different image configurations to load easily. Behavior for tools I work on has different behaviors for various reasons that are subtle when running in let's say alma8 vs ubuntu, vs Fedora. It would be of great value for the community to be able to define a set of supported operating environments in the source project so anyone in the community working on that project can easily test the difference. The current limitation of only one environment is difficult to work with.

**Comment by chrmarti** [comment] 2023-03-31 05:48
This is part of the spec, implemented in the reference implementation and supported by GitHub Codespaces and the Dev Containers extension for VS Code.

**Closed by chrmarti** 2023-03-31 05:48 UTC
Labels: finalization
