### ISSUE TITLE
Modification to Container Feature breaks build

### ISSUE THREAD

**Issue by ontoneio** [devcontainers/spec#314] opened 2023-10-04 21:15 UTC
Hello, 

I am encountering a weird issue that I am getting no error messages to debug.

I made a modification to one of my features:
```json
    "ghcr.io/devcontainers/features/java:1": {
        "version": "11",
        "installMaven": true,
        "mavenVersion": "3.9.4",
+     "jdkDistro": "open"
    },
```

And now when I go to rebuild the container or rebuild the container without cache. I get a `Disconnected from Dev Container` message in the beginning of the devcontainer build and no error to view in my host system.

The problem is that when I remove the modification from above, I am still not able to build the Dev Container any more. What would be the source of such an issue and where can I look to troubleshoot this more?

**Comment by ontoneio** [comment] 2023-10-04 21:41
This is the Dev Containers Log I was able to retrieve:

```bash
[2023-10-04T21:34:05.744Z] Start: Run: C:\Program Files\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\jonmitch\.vscode\extensions\ms-vscode-remote.remote-containers-0.315.0\dist\spec-node\devContainersSpecCLI.js outdated --workspace-folder C:\Program Files\Microsoft VS Code --config c:\Users\jonmitch\AppData\Local\Temp\dev-container-tmp-2300cdc6-11df-48f1-a629-7df99b1ace1a\.devcontainer.json --output-format json --log-level debug --log-format json
[2023-10-04T21:34:05.744Z] Dev Containers 0.315.0 in VS Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d).
[2023-10-04T21:34:06.116Z] @devcontainers/cli 0.51.3. Node.js v18.15.0. win32 10.0.22621 x64.
[2023-10-04T21:34:06.116Z] Start: Run: git rev-parse --show-cdup
[2023-10-04T21:34:06.250Z] Stop (134 ms): Run: git rev-parse --show-cdup
[2023-10-04T21:34:06.539Z] Start: Run: docker-credential-desktop get
[2023-10-04T21:34:06.542Z] Start: Run: docker-credential-desktop get
[2023-10-04T21:34:06.546Z] Start: Run: docker-credential-desktop get
[2023-10-04T21:34:06.546Z] Start: Run: docker-credential-desktop get
[2023-10-04T21:34:06.546Z] Start: Run: docker-credential-desktop get
[2023-10-04T21:34:06.546Z] Start: Run: docker-credential-desktop get
[2023-10-04T21:34:06.550Z] Start: Run: docker-credential-desktop get
[2023-10-04T21:34:06.565Z] Start: Run: docker-credential-desktop get
[2023-10-04T21:34:06.566Z] Start: Run: docker-credential-desktop get
[2023-10-04T21:34:06.567Z] Start: Run: docker-credential-desktop get
[2023-10-04T21:34:06.568Z] Start: Run: docker-credential-desktop get
[2023-10-04T21:34:07.143Z] Stop (597 ms): Run: docker-credential-desktop get
[2023-10-04T21:34:07.210Z] Stop (642 ms): Run: docker-credential-desktop get
[2023-10-04T21:34:07.211Z] Stop (646 ms): Run: docker-credential-desktop get
[2023-10-04T21:34:07.222Z] Stop (676 ms): Run: docker-credential-desktop get
[2023-10-04T21:34:07.223Z] Stop (657 ms): Run: docker-credential-desktop get
[2023-10-04T21:34:07.224Z] Stop (674 ms): Run: docker-credential-desktop get
[2023-10-04T21:34:07.230Z] Stop (663 ms): Run: docker-credential-desktop get
[2023-10-04T21:34:07.231Z] Stop (685 ms): Run: docker-credential-desktop get
[2023-10-04T21:34:07.233Z] Stop (691 ms): Run: docker-credential-desktop get
[2023-10-04T21:34:07.235Z] Stop (696 ms): Run: docker-credential-desktop get
[2023-10-04T21:34:07.237Z] Stop (691 ms): Run: docker-credential-desktop get
[2023-10-04T21:34:07.638Z] Stop (1894 ms): Run: C:\Program Files\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\jonmitch\.vscode\extensions\ms-vscode-remote.remote-containers-0.315.0\dist\spec-node\devContainersSpecCLI.js outdated --workspace-folder C:\Program Files\Microsoft VS Code --config c:\Users\jonmitch\AppData\Local\Temp\dev-container-tmp-2300cdc6-11df-48f1-a629-7df99b1ace1a\.devcontainer.json --output-format json --log-level debug --log-format json

```

**Comment by ontoneio** [comment] 2023-10-04 21:55
Run again and found this more relevant log:

```bash
[2023-10-04T21:54:21.826Z] Dev Containers 0.315.0 in VS Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d).
[2023-10-04T21:54:21.826Z] Start: Run: wsl -d Ubuntu-22.04 -e wslpath -u \\wsl.localhost\Ubuntu-22.04\home\vscode\projects\web-cms
[2023-10-04T21:54:22.152Z] Stop (326 ms): Run: wsl -d Ubuntu-22.04 -e wslpath -u \\wsl.localhost\Ubuntu-22.04\home\vscode\projects\web-cms
[2023-10-04T21:54:22.249Z] Error opening dev container configurations: CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://dev-container%2B7b22686f737450617468223a225c5c5c5c77736c2e6c6f63616c686f73745c5c5562756e74752d32322e30345c5c686f6d655c5c7673636f64655c5c70726f6a656374735c5c7765622d636d73222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f7673636f64652f70726f6a656374732f7765622d636d732f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d@wsl%2Bubuntu-22.04/workspaces'
    at r.j (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:630:11395)
    at async r.exists (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:630:13602)
    at async Promise.all (index 0)
    at async vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1855:2796
```

**Comment by ontoneio** [comment] 2023-10-04 21:57
Run again and found a different log:

```bash
[2023-10-04T21:57:01.391Z] Dev Containers 0.315.0 in VS Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d).
[2023-10-04T21:57:01.391Z] Start: Run: wsl -d Ubuntu-22.04 -e wslpath -u \\wsl.localhost\Ubuntu-22.04\home\vscode\projects\web-cms
[2023-10-04T21:57:01.739Z] Stop (348 ms): Run: wsl -d Ubuntu-22.04 -e wslpath -u \\wsl.localhost\Ubuntu-22.04\home\vscode\projects\web-cms
[2023-10-04T21:57:01.833Z] Error opening dev container configurations: CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://dev-container%2B7b22686f737450617468223a225c5c5c5c77736c2e6c6f63616c686f73745c5c5562756e74752d32322e30345c5c686f6d655c5c7673636f64655c5c70726f6a656374735c5c7765622d636d73222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f7673636f64652f70726f6a656374732f7765622d636d732f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d@wsl%2Bubuntu-22.04/workspaces'
    at r.j (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:630:11395)
    at async r.exists (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:630:13602)
    at async Promise.all (index 0)
    at async vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1855:2796

```

**Comment by samruddhikhandale** [comment] 2023-10-04 22:28
Discussed this in the community slack channel. 
The issue is with the Dev Containers extension, we have https://github.com/microsoft/vscode-remote-release/issues/9060 open for tracking it. 

Closing it in favor of https://github.com/microsoft/vscode-remote-release/issues/9060

**Closed by samruddhikhandale** 2023-10-04 22:27 UTC
